### PR TITLE
Give routing dummy URL while navigating #537

### LINKED ISSUE #537: Filters visually persist between tables
**Description**:
Filter (but not sort) values visually persist between tables if breadcrumbs are used to navigate and the tables share a field (but the table contents isn't actually filtered):

datafile filter
browser back
It also seems to occur when using browser back buttons, however that may be fixed by (or at least affected by) the changes to querying as part of #461. So probably best to wait until that PR is merged before trying to fix this. I originally noticed this on that branch, but am making this a seperate issue to prevent further increasing the size of that PR.

**Acceptance criteria**:
- [ ] Navigating via any means (table links, breadcrumbs, browser) ensures that the filters' appearances matches the URL/table contents
- [ ] Compatible with upcoming changes to querying from #461

### PR DESCRIPTION
**Pull request by patrick-austin**
## Description
When navigating the hierarchy using breadcrumbs/browser buttons, if there was a query set (e.g. filters applied) then requests were sent with the new query for the old entity (for browser navigation) or the old query with the new entity (for breadcrumbs). A side effect of this was the visual appearance of the filters being outdated.

To prevent this, have modified the `location` we pass to the router so that while we are in the process of navigating we use a dummy url so that the next entity table/card isn't loaded until the query is updated. This prevents the router and query in state getting out of sync. This also meant we need to pass the view in table links to ensure we always update the query with everything we need after the location changes.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [x] Review code
- [x] Check Actions build
- [x] Review changes to test coverage
- [x] Ensure that swapping card/table view works without additional causing duplicate requests
- [x] Ensure that normal navigation (table/card links) works in card/table views with and without queries, without causing duplicate requests
- [x] Ensure that navigation using breadcrumbs works in card/table views, with and without queries, without causing duplicate requests
- [x] Ensure that navigation using browser back buttons works in card/table views with and without queries, without causing duplicate requests

## Agile board tracking
closes #537

### CODE REVIEW

**Review by VKTB — APPROVED** [review]
Works as expected. One thing that I noticed however when toggling from table to card view while in `/browse/investigations`, is that two `datagateway_common:fectch_filter_request` requests are sent. Is this expected?

**Comment by patrick-austin** [comment]
> 
> 
> Works as expected. One thing that I noticed however when toggling from table to card view while in `/browse/investigations`, is that two `datagateway_common:fectch_filter_request` requests are sent. Is this expected?

Yeah we send one for `TYPE_ID` and one for `FACILITY_ID` so it's not the same "duplication" as requesting the count, IDs or data twice.

**Comment by VKTB** [comment]
>Yeah we send one for TYPE_ID and one for FACILITY_ID so it's not the same "duplication" as requesting the count, IDs or data twice.

Ah yes, you are right, that's different.

**Comment by patrick-austin** [comment]
@VKTB Need a re-review as I had conflicts with the addition of the TextFilter in the imports.

**Review by VKTB — APPROVED** [review]

**Pull request merged**
