### PR TITLE
Feature/lucene redux actions #121

### LINKED ISSUE #121: Convert lucene query call to Redux action
Separation of concerns between the search call and the UI elements.

### PR DESCRIPTION
**Pull request by GoelBiju**
## Description
This pull request moves the lucene related actions into `datagateway-common` allowing for other plugins to make use of the Lucene actions along with `datagateway-search`. The query parameter builder has also been moved out and new redux actions have been added to `datagateway-search` to make use of the generalised lucene redux actions.

## Testing instructions

- [x] Review code
- [x] Check Travis build
- [x] Review changes to test coverage

## Agile board tracking
Closes #121

### CODE REVIEW

**Comment by GoelBiju** [comment]
This pull request needs updated tests:

- [ ] `lucene` tests in `datagateway-common`,
- [ ] `dgcommon` reducer tests in `datagateway-common`.

**Comment by GoelBiju** [comment]
@louise-davies @tswinb I have had a look at this pull request and can't seem to see why the [build](https://travis-ci.org/github/ral-facilities/datagateway/jobs/723511728) won't pass. It seems to be because of a TypeError stating "the property default is undefined". It seems to be occuring on the `downloadApi` test in `datagateway-download`.

**Comment by agbeltran** [comment]
Hi @louise-davies - what is the situation with this PR, please?

**Comment by louise-davies** [comment]
@agbeltran It was part of the process of integrating search with dataview to allow for searching in dataview (by moving lucene actions to common). I'll resolve merge conflicts and have a look at the progress

**Comment by patrick-austin** [comment]
Fixed the broken imports which were causing the build to fail, merged and resolved conflicts with recent changes (mostly how we handle not specifying a start/end date), wrote (and fixed failing) tests. The original PR had a lot of changes to the order of imports but most of the time nothing has actually been removed or added.

Should test that searching (and the use of date filters particularly) still works as it did before, but there shouldn't be any functional change as this was just a refactor.

**Review by louise-davies — APPROVED** [review]

**Pull request merged**
