### PR TITLE
Improve tooltips and fix lingering tooltips #878

### LINKED ISSUE #878: Issue with labels when hovering on investigations titles
**Description**:
The steps I followed were:
- on the search page, select start and end date (I search for a years' worth of data - see screenshot)
- on the search results, hover over the titles of investigations

 
Screenshot 2021-10-22 at 18 07 17

**Acceptance criteria**:
- [ ] resolve issue with information found when hovering on investigation titles

### PR DESCRIPTION
**Pull request by louise-davies**
## Description
I noticed the study table tooltips weren't great as they weren't rendering the investigation title text, and that if you made a column smaller the tooltips wouldn't recalculate whether they needed to be active. So I fixed these problems, and as a side effect fixed #878 as that is effectively the opposite - that tooltips weren't recalculating when a column grew too big. I also simplified the tooltip component as the arrow styling was eventually made a prop in material ui and so I removed it here and added the prop instead.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] Verify that issue #878 no longer occurs, as well as better resizing behaviour and that the study view displays tooltips for investigation title

## Agile board tracking
Fixes #878

### CODE REVIEW

**Comment by AkhilMag13** [comment]
I have tested this for the #878 but I can still see the lingering tooltips. 
image

**Review by AkhilMag13 — CHANGES_REQUESTED** [review]
@louise-davies I have tested this for the #878 but I can still see the lingering tooltips. 
image

**Comment by louise-davies** [comment]
@AkhilMag13 did you run `yarn tsc` before testing? As I tested on both dataview and search, in both datagateway-only mode and datagateway-in-scigateway mode and it works

tooltips-dataview

tooltips-search

**Review by AkhilMag13 — APPROVED** [review]

**Comment by AkhilMag13** [comment]
I have tested it again after running yarn tsc and this made it work as expected in both `Search` and `Dataview`

**Pull request merged**
