### PR TITLE
render study pid as link #857

### LINKED ISSUE #857: Study views need to render DOI as a link
**Description**:
Currently the DOI field is rendered as text, but it needs to be rendered as a link to be useful

**Acceptance criteria**:
- [ ] Study views should render the doi field as a link

### PR DESCRIPTION
**Pull request by joshuadkitenge**
## Description
Rendering the Experimental DOIs and Parent DOIs as links. Add a link to the name on  isis studies table  to match with the Isis investigations table.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes #857

### CODE REVIEW

**Comment by MRichards99** [comment]
I remember the other day you said about having `study.pid` populated for the preprod data. Do you still need this?

**Comment by joshuadkitenge** [comment]
Yes, I would also need the parent doi as well. Currently, neither of these currently show up on the dev instance. So I can test if my Implementation works as expected.

**Comment by louise-davies** [comment]
study.pid and investigation.doi

**Comment by MRichards99** [comment]
Investigation DOIs are filled in on preprod:
`http://{{datagateway-api}}/investigations/count?where={"doi": {"like": ""}}`

That request returns 239, which is the total number of investigations for the preprod data. I'll look at study.pid :)

**Comment by MRichards99** [comment]
Could you provide screenshots of where links should be rendered please? Once `study.pid` is available on preprod data, will you be adding e2e tests to this branch?

**Comment by MRichards99** [comment]
@joshuadkitenge it's all good, I think I've found all the changes, just got a bit confused comparing my instance to ISIS prod! You don't need to provide screenshots, just let me know if you plan to add e2e tests once the study PID stuff has gone onto preprod.

**Comment by joshuadkitenge** [comment]
Yes, I would be adding e2e test on this branch.
<br><br>
Here is how it looks on production 

Screenshot 2021-11-12 104803
<br><br>


Screenshot 2021-11-12 104652
<br><br>
here is how it currently looks on preprod

Screenshot 2021-11-12 104747

Screenshot 2021-11-12 104719

Here is an example of the parent DOI on production 
Screenshot 2021-11-12 104933

**Review by MRichards99 — APPROVED** [review]

**Pull request merged**
