### PR TITLE
Align Clear filter and role selector buttons #1126

### LINKED ISSUE #1126: Role selector and clear filters button on different lines
**Description**:
On the my data view, the role selector and the clear filters button are on different lines. They should be on the same line to look better styling wise

**Acceptance criteria**:
- [ ] My data view has role selector and clear filters button on same line

### PR DESCRIPTION
**Pull request by joshuadkitenge**
## Description
- Aligning the role selector drop down menu and the clear filters button

- Moving the clear filters and the view buttons into common 

-  Defining aria-label in common for the cart instead of in search and data view respectively 

- adding a minimum height to table view to satisfy WCAG 2.1 Reflow. This will allow the table view to zoom into up to 400%  
#738

-  Changing the body to use fit-content instead of an arbitrary value /ral-facilities/scigateway/pull/959 

- ^^ Edited: ral-facilities/scigateway/issues/965
## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [x] Review code
- [x] Check Actions build
- [x] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes #1126

### CODE REVIEW

**Review by louise-davies — CHANGES_REQUESTED** [review]
The code looks good, however I have some weird misaligned vertical spacing on my end:

image

This happens both standalone DGW and with DGW hosted in SGW

**Comment by joshuadkitenge** [comment]
> 
I've checked on my side, and it still seems to be aligned on DGW and on DGW hosted on SGW. 
 
image

image

**Comment by joshuadkitenge** [comment]
I found the problem, the fix I did only works on chrome

**Comment by louise-davies** [comment]
@joshuadkitenge I think it's a firefox thing, as when I load it in chrome it looks aligned. Either that or it's one of my extensions 😅 Can you check it out on firefox to confirm?

**Review by louise-davies — APPROVED** [review]
This now works in FF :+1:

**Pull request merged**
