### PR TITLE
Feature/dls browse view #23

### LINKED ISSUE #23: Create DLS configured browse view tables
Create the Diamond browse hierarchy of `Proposal > Visit > Dataset > Datafile` with their configured columns and details panels.

Connected to ral-facilities/datagateway-userstories/issues/63

### PR DESCRIPTION
**Pull request by louise-davies**
## Description
Created the configured Diamond tables. This required adding "details" requests that are triggered when the user opens a details panel, as well as modifying some of the redux actions to be re-used in multiple situations (e.g. additional filters for `fetchInvestigations`). I also tidied up the typings of the ICAT schema, and rather than fetching dataset/fileCounts + fetching sizes being feature switches set in the settings files, I made them parameters to the redux functions themselves so it is up to each configuration of a table to decide what data it wants to fetch.

NOTE: I haven't made e2e tests for this branch yet - either this should wait for that before being merged or a separate issue should be made to track these. Others can have a go at adapting the e2e tests for these new tables if they'd like :)

## Testing instructions

- [x] Review code
- [x] Run app and explore the Diamond views (go to `/browse/proposal`)
- [x] Check tests pass
- [x] Review changes to test coverage

## Agile board tracking
Closes #23

### CODE REVIEW

**Comment by GoelBiju** [comment]
@louise-davies I have pushed all the relevant end-to-end tests for this branch.

**Comment by GoelBiju** [comment]
@louise-davies is there anything else to finish on this branch or is it ready for review to merge?

**Comment by louise-davies** [comment]
It's ready for me (I have reviewed the DLS e2e tests and they're fine) - I can't review it since it's my pull request

**Comment by GoelBiju** [comment]
@louise-davies alright no problem, I'll review it. :smiley:

**Comment by louise-davies** [comment]
For some reason the codecov bot won't publish a report for this PR, so view it here: https://codecov.io/gh/ral-facilities/datagateway/pull/62

**Pull request merged**
