### PR TITLE
React 17 and MUIv5 upgrade #830 #1096

### LINKED ISSUE #830: Upgrade to React 17
**Description**:

At present in DataGateway we are using React 16.13.1. With the release of React 17, it would be ideal to upgrade to the newer version. The official [blog post](https://reactjs.org/blog/2020/10/20/react-v17.html) highlights the benefits of upgrading.

The only issue preventing an upgrade at the moment is there not being an official Enzyme adapter for React 17. There is an issue on the Enzyme repository (https://github.com/enzymejs/enzyme/issues/2429) which is currently in progress. This upgrade would have to wait until that is officially created.

I have created a matching issue in SciGateway for upgrading to React 17 (https://github.com/ral-facilities/scigateway/issues/768). Both will need to be upgraded at the same time.

**Acceptance criteria**:

- [ ] Upgrade DataGateway to React 17 (upgrade react and react-dom, check other packages too),
- [ ] Ensure types for React is up to date,
- [ ] Enzyme Adapter is updated for React 17.

### LINKED ISSUE #1096: Upgrade to MUI v5
**Description**:
Upgrade to MUI v5 following https://mui.com/guides/migration-v4/.

**Acceptance criteria**:
- [ ] Upgraded to MUI v5

### LINKED ISSUE #1155: `yarn install --production` not working
**Description**:
When installing the dependencies in data gateway using `yarn build --production` the following error is produced:
```
 > [5/5] RUN yarn build:
#9 0.459 yarn run v1.22.17
#9 0.535 $ lerna run build --ignore datagateway-common
#9 1.203 lerna notice cli v4.0.0
#9 1.270 lerna notice filter excluding "datagateway-common"
#9 1.272 lerna info filter [ '!datagateway-common' ]
#9 1.276 lerna info Executing command in 3 packages: "yarn run build"
#9 37.20 lerna ERR! yarn run build exited 1 in 'datagateway-search'
#9 37.20 lerna ERR! yarn run build stdout:
#9 37.20 $ craco build
#9 37.20 Creating an optimized production build...
#9 37.20 Failed to compile.
#9 37.20
#9 37.20 ./src/index.tsx
#9 37.20 Cannot find module: 'datagateway-common'. Make sure this package is installed.
#9 37.20
#9 37.20 You can install this package by running: yarn add datagateway-common.
#9 37.20
#9 37.20
#9 37.20 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#9 37.20 lerna ERR! yarn run build stderr:
#9 37.20 error Command failed with exit code 1.
#9 37.20 lerna ERR! yarn run build exited 1 in 'datagateway-search'
#9 37.20 lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
#9 37.23 error Command failed with exit code 1.
#9 37.23 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Presumably, it's not installing the correct dependencies due to the fact that:
> --production
> Only install regular dependencies by omitting dev dependencies

The error is reproduced with the following high level `package.json`:
```
{
  "name": "datagateway",
  "private": true,
  "version": "0.1.0",
  "workspaces": [
    "packages/*"
  ],
  "devDependencies": {
    "husky": "^7.0.4",
    "lerna": "^4.0.0",
    "lerna-update-wizard": "^1.1.0"
  },
  "scripts": {
    "prepare": "lerna run prepare",
    "build": "lerna run build --ignore datagateway-common",
    "lint": "lerna run lint:js -- --max-warnings=0",
    "tsc": "lerna run tsc",
    "test": "yarn test:unit && yarn test:e2e",
    "test:unit": "lerna run test --stream",
    "test:e2e": "cd packages/datagateway-dataview && yarn run e2e && cd ../datagateway-download && yarn run e2e && cd ../datagateway-search && yarn run e2e",
    "test:e2e:lerna": "lerna run e2e --stream --concurrency 1",
    "datagateway-dataview": "cd packages/datagateway-dataview && yarn start",
    "datagateway-download": "cd packages/datagateway-download && yarn start",
    "datagateway-search": "cd packages/datagateway-search && yarn start",
    "postinstall": "husky install"
  },
  "dependencies": {
    "husky": "^7.0.4",
    "lerna": "^4.0.0"
  }
}
```
using the following docker file to run the project:
```
FROM node:14-alpine as build
WORKDIR /datagateway
ENV PATH /datagateway/node_modules/.bin:$PATH
copy . .

RUN yarn install --production

RUN yarn build
```
**Acceptance criteria**:
- [ ] Update the list of dependencies in the `"dependencies": {}` section of each of the plugins' `package.json` file.
- [ ] make sure the build passes with `RUN yarn install --production`

### PR DESCRIPTION
**Pull request by joelvdavies**
## Description
Upgrades React 16 to 17, MUIv4 to v5 and yarn to yarn 2.

## Notes
- Simplified tooltip as close on escape now handled by MUI
- Refactored styling to use the new sx prop and `styled` instead of `style` (for MUI components only) and `makeStyles` (see https://mui.com/guides/migration-v4/#migrate-from-jss)
- Removed `generateClassNames` in App.tsx files as should no longer be necessary since emotions class names are hash based (I have not seen any evidence of collisions so far)
- Investigated https://github.com/ral-facilities/datagateway/issues/821 and it is still broken, it seems the position will not update without the resize event, only the width
- Emotion is now used for creating animations for `mark/sticky/selectionAlertBanner' in common
- Have added `searchTabs` component to replace `seachPageTable` & `searchCardView` as previously the tabs and their styling were defined twice making the code harder to maintain
- Have installed and used `@testing-library/react` in a few places, particularly where there were giant snapshots that got even bigger after the upgrade (e.g. `downloadConfirmDialog`) as testing-library resolves to standard html elements in snapshots instead of MUI ones with tonnes of styling
- Date pickers now use @mui/lab - by default in testing these pickers end up using their mobile counterparts so have added an 'applyDatePickerWorkaround' function in setupTests.tsx which applies a workaround so that they render as desktop date pickers otherwise their contents can't be changed in tests
- Have upgraded to yarn 2 as this fixed an issue with installing the latest @mui/lab (following https://yarnpkg.com/getting-started/migration)

## Dev Environment Changes
- Due to the yarn 2 upgrade you may want follow step 1 in https://yarnpkg.com/getting-started/migration to ensure you are also using the latest yarn - I had to use https://stackoverflow.com/questions/57673913/vsc-powershell-after-npm-updating-packages-ps1-cannot-be-loaded-because-runnin as well

## Testing instructions
Test with https://github.com/ral-facilities/scigateway/pull/930.

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes #830, Closes #1096, Closes #1155

### CODE REVIEW

**Comment by sam-glendenning** [comment]
Update on where I am on this - had a look at DG common and made a few amendments. Next, I'll have a look at fixing merge conflicts

**Comment by louise-davies** [comment]
TODO: refactor datefilter datetime picker to allow users to select seconds

**Comment by sam-glendenning** [comment]
> TODO: refactor datefilter datetime picker to allow users to select seconds

This will be tackled in a separate issue - https://github.com/ral-facilities/datagateway/issues/1227

**Comment by sam-glendenning** [comment]
TODO: change `ReactDOM.render` in `index.tsx` to `ReactDOM.createRoot` instead (`render` is deprecated in React 18, possibly React 17). See OperationsGateway's method of doing things - https://github.com/ral-facilities/operationsgateway/blob/f031b76c8a2c18dac532099e0cc442235f2deea1/src/index.tsx#L15

**Comment by sam-glendenning** [comment]
I have reviewed all the code in this PR as of 17th May. The current plan is to not release the upgrade until after the Diamond release, roughly scheduled to take place in mid-June. Following this, a full-scale site review and test will take place involving myself and Louise. Once this is successfully complete, this code will be merged.

**Comment by louise-davies** [comment]
Issues to be fixed:

Cart page 'footer' is misaligned:
image

Landing page download button is misaligned:
image

Loading bar in search view causes scrollbar to appear

**Comment by louise-davies** [comment]
I'm now pretty confident that things are fine in both SG and DG - I have done pretty extensive testing (as can be seen by the minor fixes I've been making) and at this point anything left will likely be either a very niche issue or very minor such that I couldn't detect it.

@sam-glendenning you happy for this to go in?

**Comment by sam-glendenning** [comment]
@louise-davies I'll have a little go with it tomorrow and let you know then

**Review by sam-glendenning — APPROVED** [review]
@louise-davies as God is my witness, these PRs are ready for merge!

**Pull request merged**
