### PR TITLE
Feature/download confirmation #49

### LINKED ISSUE #49: [datagateway-download] Create download confirmation view
This is a large issue that may get split up into smaller issues.

Recreate the TopCAT download confirmation view. This is accessed when the user clicks download on the cart page, and they should be redirected to this page.

Download confirmation mockup (based on current TopCAT):
confirm download

Acceptance Criteria:
- [x] Allows the user to rename their download cart
- [x] Allows the user to select the download type
- [x] If the user cancels it sends them back to the cart view
- [x] If the user downloads then it should submit the download request
- [x] Users can supply their email and they will be emailed once their download has finished

### LINKED ISSUE #101: [datagateway-download] Disable 'Download Cart' button when cart is empty
Currently the 'Download Cart' button opens even when the cart is empty.

Acceptance criteria:

- [x] 'Download Cart' button is disabled when the cart contains no items.

### PR DESCRIPTION
**Pull request by GoelBiju**
## Description
This feature adds in a confirmation modal dialog which allows for a user to confirm the download of the items in their cart. The submission of the download submits a download request and depending on the type of access method selected, starts an IDS file download. This also provides a link to the status download page for #48 upon a successful download request submission.

## Testing instructions

- [x] Review code
- [x] Check Travis build
- [x] Review changes to test coverage

## Agile board tracking
Closes #49, Closes #101

### CODE REVIEW

**Comment by GoelBiju** [comment]
This pull request still needs the component tests written and additional minor tweaks to the code (in terms of UI layout).

**Comment by esl-lewis** [comment]
> 
> 
> The confirmation download modal acts as expected. Though I found that the globus download is always successful while https fails. Is this expected behaviour?
> 
> Also when adding files via scigateway-preprod I found that downloading the cart did not update the tabs to uncheck on the table. I also then found that after the download, adding files via tabs stopped working completely and I lost the ability to select mutliple files at one point. This error may be beyond the scope of this PR but is a point worth mentioning.

Have established that the first issue was a mistake on my end and the second cannot be replicated so may have been just a poor connection or to do with refreshing so I will not make an issue. 

Otherwise all good 😄 though I suggest the cart automatically refreshes after a REMOVE ALL or DOWNLOAD action to keep the user updated.

**Comment by GoelBiju** [comment]
> > The confirmation download modal acts as expected. Though I found that the globus download is always successful while https fails. Is this expected behaviour?
> > Also when adding files via scigateway-preprod I found that downloading the cart did not update the tabs to uncheck on the table. I also then found that after the download, adding files via tabs stopped working completely and I lost the ability to select mutliple files at one point. This error may be beyond the scope of this PR but is a point worth mentioning.
> 
> Have established that the first issue was a mistake on my end and the second cannot be replicated so may have been just a poor connection or to do with refreshing so I will not make an issue.
> 
> Otherwise all good 😄 though I suggest the cart automatically refreshes after a REMOVE ALL or DOWNLOAD action to keep the user updated.

It could have been due to me using the preprod simultaneously or the CI. This could be an enhancement for the download cart table @louise-davies . It supports actions to individual items but without a refresh the user may not necessarily know if there are any updates to the table, the same could be applied to the download status table.

**Comment by louise-davies** [comment]
@GoelBiju @esl-lewis Are you talking about adding files from the table view in one tab and viewing the download cart in another? I'm not sure if we need/want to support that sort of parallelism. Either way it should not be a blocking issue.

**Comment by esl-lewis** [comment]
> 
> 
> @GoelBiju @esl-lewis Are you talking about adding files from the table view in one tab and viewing the download cart in another? I'm not sure if we need/want to support that sort of parallelism. Either way it should not be a blocking issue.

Yeah I agree, I'm not sure if the user would want feedback between the download cart and table checkboxes.

**Comment by GoelBiju** [comment]
> @GoelBiju @esl-lewis Are you talking about adding files from the table view in one tab and viewing the download cart in another? I'm not sure if we need/want to support that sort of parallelism. Either way it should not be a blocking issue.

I was really just thinking about the cart updating after actions are performed but at the moment it will require a refresh on the page.

**Comment by louise-davies** [comment]
@GoelBiju which actions? currently the only thing a user can do is remove something from the cart, which updates in real time (it both sends a request to the server and removes the item from the user's view), and download the cart in total.

**Comment by GoelBiju** [comment]
> @GoelBiju which actions? currently the only thing a user can do is remove something from the cart, which updates in real time (it both sends a request to the server and removes the item from the user's view), and download the cart in total.

Maybe I was thinking of what happens after you click the download in the confirmation, the cart item at the moment appears to still be in the cart but requires a refresh for the user to know it has been removed. That could be something to add into this branch?

**Comment by louise-davies** [comment]
@GoelBiju The cart items should be removed. The way TopCAT dealt with this is due to the cart itself being a modal and thus closing the download confirmation modal would cause the next view of the cart to load from the server again, thus displaying an empty cart. Perhaps passing an `clearCart` method to the confirmation component which calls `setData([])`, which is called when the download submission has been successful?

**Comment by GoelBiju** [comment]
> @GoelBiju The cart items should be removed. The way TopCAT dealt with this is due to the cart itself being a modal and thus closing the download confirmation modal would cause the next view of the cart to load from the server again, thus displaying an empty cart. Perhaps passing an `clearCart` method to the confirmation component which calls `setData([])`, which is called when the download submission has been successful?

I have just added this change to the pull request.

**Comment by GoelBiju** [comment]
> Wouldn't this clear the data from the cart even if the download was unsuccessful?

@louise-davies you are completely right, I forgot that it would clear all the items regardless. I'll change it so that it is only invoked when the download is successful.

**Comment by esl-lewis** [comment]
> 
> 
> > Wouldn't this clear the data from the cart even if the download was unsuccessful?
> 
> @louise-davies you are completely right, I forgot that it would clear all the items regardless. I'll change it so that it is only invoked when the download is successful.
> 
> This has now been corrected in [cb80d98](https://github.com/ral-facilities/datagateway/commit/cb80d98fb5ca0aa5a9bf0314651496f98f0706f3).

@GoelBiju I'd like to test an unsuccessful download before approving, do you have any suggestions for forcing a download failure?

**Comment by esl-lewis** [comment]
> 
> 
> > > Wouldn't this clear the data from the cart even if the download was unsuccessful?
> > 
> > 
> > @louise-davies you are completely right, I forgot that it would clear all the items regardless. I'll change it so that it is only invoked when the download is successful.
> > This has now been corrected in [cb80d98](https://github.com/ral-facilities/datagateway/commit/cb80d98fb5ca0aa5a9bf0314651496f98f0706f3).
> 
> @GoelBiju I'd like to test an unsuccessful download before approving, do you have any suggestions for forcing a download failure?

Please ignore this, @louise-davies gave me a pointer

**Comment by GoelBiju** [comment]
> > > Wouldn't this clear the data from the cart even if the download was unsuccessful?
> > 
> > 
> > @louise-davies you are completely right, I forgot that it would clear all the items regardless. I'll change it so that it is only invoked when the download is successful.
> > This has now been corrected in [cb80d98](https://github.com/ral-facilities/datagateway/commit/cb80d98fb5ca0aa5a9bf0314651496f98f0706f3).
> 
> @GoelBiju I'd like to test an unsuccessful download before approving, do you have any suggestions for forcing a download failure?

Maybe you could try adding an item to the download cart and open the download confirmation dialog in one tab. In another tab open the download cart but remove the item from the cart. That may work and fail to return a downloadId in which it should show an unsuccessful download request @esl-lewis .

**Pull request merged**
