### PR TITLE
Adjust height calculations in various components

### PR DESCRIPTION
**Pull request by kennethnym**
## Description
This PR includes fixes for some height miscalculations:
- admin download status table in `datagateway-download`: content overflows slightly when the progress bar appears
- `PageContainer` in `datagateway-dataview`: slightly too short causing a white bar appear underneath tables

Related: https://github.com/ral-facilities/scigateway/pull/1121

## Testing instructions
- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
connect to https://github.com/ral-facilities/scigateway/pull/1121

### CODE REVIEW

**Review by sam-glendenning — CHANGES_REQUESTED** [review]
Ahhh I hate to be that guy but it's still not _quite_ perfect. I'm still seeing a little bit of cutoff at the bottom of pages in dataview. I think it _may_ be caused by the breadcrumbs wrapping onto a new line so this may need to be factored into the calculation as well.

So here it is currently with one line of breadcrumbs:

image

And here it is with another line of breadcrumbs added:

image

**Comment by kennethnym** [comment]
Hi Sam, The bottom cut-off issue is already present in preprod:

image

**Comment by sam-glendenning** [comment]
Hold on @kennethnym, before you do, lemme just say - 

- scigateway-preprod, while used in e2e testing, is very out of date as a build. It has not been updated in many months. I would refer to one of the production URLs, such as https://data.isis.stfc.ac.uk, for the latest (and greatest) build
- According to those production builds, I personally can't see the cutoff. If you can, let me know what browser and magnification you're using and, if it still exists, we can make an issue for it

**Comment by kennethnym** [comment]
I visited the URL and went to the "Facility Cycles" page, and this is what I am seeing:

image

As you can see, there is a bit of a cut off at the bottom of the table, and also bottom padding below the card/paper holding the table.

**Review by sam-glendenning — APPROVED** [review]
Tested with https://github.com/ral-facilities/scigateway/pull/1121 and it works well!

**Comment by kennethnym** [comment]
image

The parent of the table is utilizing the full height available, so I think the cut off is a separate issue of its own. I can create a new issue for it!

**Pull request merged**
