### PR TITLE
Configurable number of search results #948

### PR DESCRIPTION
**Pull request by joelvdavies**
## Description
Adds a setting `maxNumResults` in search to make the maximum number of search results returned configurable. This value is also used in the text presented to the user.

image
image

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [x] Review code
- [x] Check Actions build
- [x] Review changes to test coverage

## Agile board tracking
connect to #948

### CODE REVIEW

**Comment by agbeltran** [comment]
@joelvdavies I was wondering where is the second screenshot (Limited results) is coming from?

**Comment by joelvdavies** [comment]
@agbeltran This is at the bottom of the advanced help dialogue. The message in the first screenshot says to 'Click on advanced to learn more' about why there is a limit. I believe this was feedback I got from one of the sprint review meetings at the time.

**Comment by agbeltran** [comment]
thanks @joelvdavies ! I assume you made sure that the number of results is also configured in that text. Cheers

**Comment by joelvdavies** [comment]
@agbeltran Yes I have, thanks.

**Review by louise-davies — APPROVED** [review]
Looks good and all the places that use the number have been updated to use the config variable

**Pull request merged**
